     CC='/root/.ppkg/core/wrapper-target-cc'
   OBJC='/root/.ppkg/core/wrapper-target-cc'
    CXX='/root/.ppkg/core/wrapper-target-c++'
     AS='/usr/bin/as'
     AR='/usr/bin/ar'
 RANLIB='/usr/bin/ranlib'
     LD='/usr/bin/ld'
     NM='/usr/bin/nm'
   SIZE='/usr/bin/size'
  STRIP='/usr/bin/strip'
STRINGS='/usr/bin/strings'
OBJDUMP='/usr/bin/objdump'
OBJCOPY='/usr/bin/objcopy'
READELF='/usr/bin/readelf'
SYSROOT=''

CCFLAGS=' -Os '
LDFLAGS='-static --static -ffunction-sections -fdata-sections -Wl,--gc-sections -L/root/.ppkg/run/2855/linux-musl-x86_64/uctags/lib -Wl,--as-needed -Wl,-z,muldefs -Wl,--allow-multiple-definition -flto -Wl,-s -L/root/.ppkg/installed/linux-musl-x86_64/libjansson/lib -Wl,-rpath,/root/.ppkg/installed/linux-musl-x86_64/libjansson/lib -L/root/.ppkg/installed/linux-musl-x86_64/libyaml/lib -Wl,-rpath,/root/.ppkg/installed/linux-musl-x86_64/libyaml/lib -L/root/.ppkg/installed/linux-musl-x86_64/libiconv/lib -Wl,-rpath,/root/.ppkg/installed/linux-musl-x86_64/libiconv/lib -L/root/.ppkg/installed/linux-musl-x86_64/libz/lib -Wl,-rpath,/root/.ppkg/installed/linux-musl-x86_64/libz/lib -L/root/.ppkg/installed/linux-musl-x86_64/libxml2/lib -Wl,-rpath,/root/.ppkg/installed/linux-musl-x86_64/libxml2/lib'
